[pytest]
pythonpath = .

addopts = --alluredir=allure-results

markers =
    web: marks web-related tests
    wikipedia: tests that involve wikipedia pages
    positive: positive path examples
    negative: negative path examples (expected to fail / xfail)
